defaults:
  - base_data

drive_path: 'MyDrive/CT-ORG.zip'
base_path: "${oc.env:TOP_PROJECT_PATH}/pytorch/extern/data/CT-ORG/"
scan_pattern: "volume-*.nii.gz"
cache_path: "${jobs.load_data.base_path}/cache/"
desired_size: [192,96,192]
patch_size: [192,96,192]
num_classes: 6
batch: 10
dataset: CTORGDataset