defaults:
  - data: 
    - defaults
    - tcia-ct-scan
  - hparams:
    - UNet3D
  - /hydra/callbacks:
    - data_callback
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: nevergrad