defaults:
  - data:
    - generic
    - tcia-ct-scan
  - hparams:
    - generic
    - UNet3Dsmall
  - /hydra/callbacks:
    - data_callback
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: nevergrad