defaults:
  - data: tcia-ct-scan
  - hparams:
    - data
  - /hydra/callbacks:
    - data_callback
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: nevergrad