defaults:
  - jobs:
    # - load_data
    - load_model
    # - train
    - deploy
  - /hydra/callbacks:
    - data_callback
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: nevergrad