defaults:
  - data:
    - generic
    - tcia_ct_scan
  - hparams:
    - generic
    - UNet3D
  - /hydra/callbacks:
    - data_callback
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: nevergrad